### PR TITLE
Execute create uploader inline

### PR DESCRIPTION
**Pull request by tralles**
This might be a regression, because using `content_for :scripts` and using the `page:load` event was used to fit turbolinks – but I've to renovate the upload process by switching from Fine Uploader 3.8 to the current 5.5 (which needs more adaptations), so the advantage of this fix outweigh the disadvantages of waiting for the uploader update..

### CODE REVIEW

**Comment by paulmenzel** [comment]
Wasn’t there an Giant Monkey OpenProject work package for that issue?

**Comment by tralles** [comment]
yes @paulmenzel, there is a internal ticket, but i was not convinced to reference properitary workpackages in an open source project …

**Comment by paulmenzel** [comment]
For reference, the internal Giant Monkey ticket is [#4448](https://projects.giantmonkey.de/work_packages/4448).

**Comment by paulmenzel** [comment]
In my opinion, the work packages can be referenced. Ideally, only GitHub’s issues tracker is usesd.

**Pull request merged**
